-- ============================================
-- AI Trade Supabase Schema
-- Migration: 001_initial_schema
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    telegram_id TEXT UNIQUE NOT NULL,
    username TEXT,
    first_name TEXT,
    is_whitelisted BOOLEAN DEFAULT FALSE,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for users
CREATE INDEX IF NOT EXISTS idx_users_telegram_id ON users(telegram_id);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_whitelisted ON users(is_whitelisted) WHERE is_whitelisted = TRUE;

-- ============================================
-- SIGNALS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_telegram_id TEXT NOT NULL REFERENCES users(telegram_id) ON DELETE CASCADE,
    pair TEXT NOT NULL,
    pair_symbol TEXT,
    direction TEXT NOT NULL CHECK (direction IN ('UP', 'DOWN')),
    timeframe INTEGER NOT NULL CHECK (timeframe > 0),
    accuracy INTEGER NOT NULL CHECK (accuracy >= 0 AND accuracy <= 100),
    entry_price DECIMAL(20, 8),
    exit_price DECIMAL(20, 8),
    result TEXT CHECK (result IN ('WIN', 'LOSE', 'NEUTRAL', 'CANCEL')),
    ai_reason TEXT,
    entry_time TIMESTAMPTZ,
    expiry_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for signals
CREATE INDEX IF NOT EXISTS idx_signals_user_telegram_id ON signals(user_telegram_id);
CREATE INDEX IF NOT EXISTS idx_signals_created_at ON signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_result ON signals(result);
CREATE INDEX IF NOT EXISTS idx_signals_pair ON signals(pair);

-- ============================================
-- CHAT MESSAGES TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS chat_messages (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_telegram_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    tokens_used INTEGER,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for chat_messages
CREATE INDEX IF NOT EXISTS idx_chat_messages_user_telegram_id ON chat_messages(user_telegram_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON chat_messages(created_at DESC);

-- ============================================
-- UPDATED_AT TRIGGER
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to users table
DROP TRIGGER IF EXISTS update_users_updated_at ON users;
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- COMMENTS
-- ============================================
COMMENT ON TABLE users IS 'Telegram users with whitelist status';
COMMENT ON TABLE signals IS 'Trading signals generated by AI';
COMMENT ON TABLE chat_messages IS 'AI chat conversation history';

COMMENT ON COLUMN users.telegram_id IS 'Unique Telegram user ID';
COMMENT ON COLUMN users.is_whitelisted IS 'Whether user has access to the app';
COMMENT ON COLUMN signals.direction IS 'Trading direction: UP or DOWN';
COMMENT ON COLUMN signals.result IS 'Signal outcome: WIN, LOSE, NEUTRAL, or CANCEL';
